### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by R533-Code** [R533-Code/colt-cpp#176]
- [ ] `VirtualLock` (`mlock` on Linux)
- [ ] Add missing linux implementations
- [ ] `ViewOfFile` from `File`
- [ ] Unicode database python parsing
